# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

hand_position_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - gripper_joint
  gains:
    gripper_joint: 
        p: 5 
        i: 0.0 
        d: 0.0
        i_clamp: 1
  # joints:
    # - gripper_joint
    # - r_finger_1_joint
    # - l_finger_2_joint
    # - r_finger_2_joint
  # gains:
  #   gripper_joint:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #     antiwindup: false
  #     publish_state: true
  #   r_finger_1_joint:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #     antiwindup: false
  #     publish_state: true
    # l_finger_2_joint:
    #   p: 100
    #   d: 1
    #   i: 1
    #   i_clamp: 1
    
    # r_finger_2_joint:
    #   p: 100
    #   d: 1
    #   i: 1
    #   i_clamp: 1